addr: :9000
gin_mode: "debug"
#gin_mode: "release"

dsn: "goblog:goblog123@tcp(127.0.0.1:3306)/goblog?charset=utf8mb4&parseTime=True&loc=Local"
max_idle_conn: 100
sql_debug: true

sql_lite: "blog.db"

jwt_secret: "your secret"
jwt_expire_day: 30

redis_host: "127.0.0.1:6379"
redis_password:
redis_max_idle: 30
redis_active: 30
redis_idle_timeout: 200

rabbit_host: "amqp://tomaxut:1635358408@114.132.167.155:5672/tomaxut"